# Generated by Django 2.0 on 2018-05-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, height_field=20, upload_to='', width_field=20),
        ),
    ]
