# Generated by Django 2.0 on 2018-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20180505_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='20', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='20', editable=False, null=True),
        ),
    ]
