# Generated by Django 2.0 on 2018-05-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20180505_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_width',
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, height_field=models.PositiveIntegerField(blank=True, default='20', editable=False, null=True), upload_to='', width_field=models.PositiveIntegerField(blank=True, default='20', editable=False, null=True)),
        ),
    ]
