# Generated by Django 2.0 on 2018-05-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180505_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
